services:
  postgres:
    image: postgres:16-alpine
    container_name: elysia-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_crud_with_elysia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: crud-with-elysia
    restart: always
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.docker
    working_dir: /app
    command: sh -c "bunx prisma migrate deploy && bun run start"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elysia-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data:
